[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib', 'test/utils']
test = 'test/foundry'
cache_path  = 'forge-cache'
optimizer = true
optimizer-runs = 10_000_000

# See more config options https://book.getfoundry.sh/reference/config.html
